// AUTO-GENERATED — do not edit by hand.
// Regenerate via `npm run generate:chained-deps` (or `npm run generate`).
// Source: scripts/generate-chained-deps.mjs

export const CHAINED_DEPS: Record<string, readonly string[]> = {
  "add-blockgrid-block": ["get-document-by-id", "update-document-properties"],
  "add-blocklist-block": ["get-document-by-id", "update-document-properties"],
  "add-rte-block": ["get-document-by-id", "update-document-properties"],
  "audit-page-content": ["get-document-by-id"],
  "audit-page-seo": ["get-document-by-id"],
  "bulk-move": ["get-document-by-id", "move-document"],
  "bulk-move-media": ["get-media-by-id", "move-media"],
  "bulk-publish": ["publish-document", "publish-document-with-descendants"],
  "bulk-schedule-publish": ["publish-document"],
  "bulk-set-block-property": ["get-document-by-id", "get-document-version", "update-block-property"],
  "bulk-set-property": ["update-document-properties"],
  "bulk-unpublish": ["get-document-by-id", "unpublish-document"],
  "cancel-schedule": ["get-document-by-id", "publish-document"],
  "copy-variant": ["get-document-by-id", "update-document"],
  "create-and-publish-page": ["create-and-publish-document", "get-data-types-by-id-array", "get-document-type-by-id"],
  "create-blueprint": ["create-document-blueprint-from-document", "get-document-blueprint-root", "get-document-by-id"],
  "create-dictionary": ["create-dictionary"],
  "create-language": ["create-language"],
  "create-media-folder": ["create-media-folder", "get-media-by-id"],
  "create-member": ["create-member", "get-member", "update-member"],
  "create-member-group": ["create-member-group"],
  "create-page": ["create-document", "get-data-types-by-id-array", "get-document-type-by-id"],
  "create-variant": ["get-document-by-id", "update-document"],
  "delete-block": ["get-document-by-id", "update-document-properties"],
  "delete-language": ["delete-language", "get-language-by-iso-code"],
  "delete-media": ["get-media-by-id", "move-media-to-recycle-bin"],
  "delete-member": ["delete-member", "get-member"],
  "delete-member-group": ["delete-member-group", "get-member-group"],
  "delete-page": ["get-document-by-id", "move-document-to-recycle-bin"],
  "delete-redirect": ["delete-redirect", "get-all-redirects"],
  "duplicate-page": ["copy-document", "get-document-by-id"],
  "edit-block": ["get-document-by-id", "update-block-property"],
  "edit-media": ["get-media-by-id", "update-media"],
  "edit-page": ["get-document-by-id", "update-document-properties"],
  "get-blueprint": ["get-document-blueprint"],
  "get-content-notifications": ["get-document-notifications"],
  "get-current-user": ["get-user-current", "get-user-group-by-id-array"],
  "get-dictionary": ["get-dictionary"],
  "get-document-type": ["get-document-type-by-id"],
  "get-language": ["get-language-by-iso-code"],
  "get-media": ["get-media-by-id", "get-media-urls"],
  "get-media-change-history": ["get-media-audit-log", "get-media-by-id", "get-user-by-id"],
  "get-media-type": ["get-media-type-by-id"],
  "get-member": ["get-member"],
  "get-page": ["get-document-by-id"],
  "get-page-change-history": ["get-document-audit-log", "get-document-by-id", "get-user-by-id"],
  "get-property-value-template": ["get-document-property-value-template"],
  "get-public-access": ["get-document-public-access"],
  "get-publish-status": ["get-document-by-id"],
  "get-redirect": ["get-redirect-by-id"],
  "get-redirect-status": ["get-redirect-status"],
  "inspect-blocks": ["get-document-by-id"],
  "list-blueprints": ["get-document-blueprint-children", "get-document-blueprint-root"],
  "list-children": ["get-document-children", "get-document-root"],
  "list-dictionary": ["get-dictionary", "get-dictionary-children", "get-dictionary-root"],
  "list-document-types": ["get-document-type-by-id", "get-document-type-children", "get-document-type-root"],
  "list-languages": ["get-language"],
  "list-media-children": ["get-media-children", "get-media-root"],
  "list-media-types": ["get-media-type-allowed-at-root", "get-media-type-allowed-children", "get-media-type-by-id"],
  "list-member-groups": ["get-all-member-groups"],
  "list-member-types": ["get-member-type-root"],
  "list-page-templates": ["get-document-by-id", "get-document-type-by-id", "get-template"],
  "list-redirects": ["get-all-redirects"],
  "list-scheduled-content": ["get-document-by-id"],
  "list-tags": ["get-tags"],
  "list-untranslated": ["get-document-by-id", "get-document-children", "get-document-root"],
  "list-versions": ["get-document-by-id", "get-document-version"],
  "move-dictionary": ["get-dictionary", "move-dictionary-item"],
  "move-media": ["get-media-by-id", "move-media"],
  "permanent-delete-recycle-bin-item": ["get-document-by-id", "get-media-by-id"],
  "publish-page": ["get-document-by-id", "publish-document", "publish-document-with-descendants"],
  "remove-public-access": ["delete-document-public-access"],
  "report-content-references": ["get-document-by-id", "get-document-by-id-referenced-by", "get-media-by-id", "get-media-by-id-referenced-by", "get-media-urls"],
  "report-deep-pages": ["get-document-children", "get-document-root"],
  "report-large-media": ["get-media-by-id", "get-media-urls"],
  "report-media-missing-alt": ["get-media-by-id", "get-media-urls"],
  "report-media-references": ["get-media-by-id-referenced-by"],
  "report-member-activity": ["find-member"],
  "report-member-count": ["find-member", "get-all-member-groups"],
  "report-members-by-group": ["find-member", "get-all-member-groups"],
  "report-orphan-pages": ["get-document-by-id-referenced-by"],
  "report-outbound-links": ["get-document-by-id"],
  "report-page-references": ["get-document-by-id-referenced-by"],
  "report-site-tree-summary": ["get-document-children", "get-document-root"],
  "report-translation-coverage": ["get-language"],
  "restore-media": ["get-media-by-id", "restore-media-from-recycle-bin"],
  "restore-page": ["get-document-by-id"],
  "rollback-page": ["create-document-version-rollback", "get-document-by-id", "get-document-version", "get-user-by-id"],
  "save-and-publish": ["get-document-by-id", "publish-document", "publish-document-with-descendants", "update-and-publish-document", "update-document-properties"],
  "schedule-publish": ["get-document-by-id", "publish-document"],
  "search-content": ["search-document"],
  "search-dictionary": ["find-dictionary"],
  "search-media": ["get-collection-media", "get-media-urls"],
  "search-members": ["find-member"],
  "set-content-notifications": ["put-document-notifications"],
  "set-page-template": ["get-document-by-id", "get-document-type-by-id", "get-template", "update-document"],
  "set-public-access": ["get-document-public-access", "post-document-public-access", "put-document-public-access"],
  "sort-children": ["sort-document"],
  "sort-media-children": ["sort-media"],
  "unpublish-page": ["get-document-by-id", "unpublish-document"],
  "update-dictionary": ["get-dictionary", "update-dictionary-item"],
  "update-language": ["get-language-by-iso-code", "update-language"],
  "update-member": ["get-member", "update-member"],
  "upload-media": ["create-media", "get-media-by-id"],
};
